apiVersion: v1
kind: Service
metadata:
  name: korus-gateway
  namespace: korus-system
  labels:
    app.kubernetes.io/name: korus-gateway
    app.kubernetes.io/part-of: korus
spec:
  selector:
    app.kubernetes.io/name: korus-controller-manager
  ports:
  - name: http
    port: 8082
    targetPort: gateway
    protocol: TCP
