// +kubebuilder:rbac:groups=windosx.com,resources=agents,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=agents/status,verbs=get;patch;update
// +kubebuilder:rbac:groups=windosx.com,resources=prompttemplates,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=knowledgebases,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=toolproviders,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=tenants,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=tenants/status,verbs=get;patch;update
// +kubebuilder:rbac:groups=windosx.com,resources=workspaces,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=workspaces/status,verbs=get;patch;update
// +kubebuilder:rbac:groups=windosx.com,resources=datasets,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=mcpservers,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=agentpolicies,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=agentruns,verbs=create;get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=agentruns/status,verbs=get;patch;update
// +kubebuilder:rbac:groups=windosx.com,resources=agentevaluations,verbs=get;list;watch
// +kubebuilder:rbac:groups=windosx.com,resources=agentevaluations/status,verbs=get;patch;update
// +kubebuilder:rbac:groups=batch,resources=jobs,verbs=create;get;list;watch;patch;update
// +kubebuilder:rbac:groups="",resources=pods,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=pods/log,verbs=get
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch
package controller
