apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-control-plane-leader-election-rolebinding
  namespace: agent-control-plane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-control-plane-leader-election-role
subjects:
- kind: ServiceAccount
  name: agent-control-plane-controller-manager
  namespace: agent-control-plane-system
