apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-control-plane-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-control-plane-manager-role
subjects:
- kind: ServiceAccount
  name: agent-control-plane-controller-manager
  namespace: agent-control-plane-system
