apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-control-plane.gatewayName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gateway"
spec:
  type: {{ .Values.gateway.service.type | quote }}
  selector:
    app.kubernetes.io/name: {{ include "agent-control-plane.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: "controller-manager"
  ports:
  - name: http
    port: {{ .Values.gateway.service.port }}
    targetPort: gateway
    protocol: TCP
