{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-control-plane.labels" . | nindent 4 }}
{{- end }}
