{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-control-plane.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-control-plane.controllerLabels" . | nindent 4 }}
{{- end }}
