{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "korus.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "korus.controllerLabels" . | nindent 4 }}
{{- end }}
